apiVersion: v1
kind: Pod
metadata: 
  name: web
spec:
  containers:
   - name: nginx
     image: nginx:1.17-alpine 
     ports:
     - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
             - worker1
             - worker2
      preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 1
         preference:
           matchExpressions:
            - key: disktype
              operator: In
              values:
               - ssd        
