apiVersion: v1
kind: Pod
metadata:
  name: web2c
  labels:
     app: web  
spec:
  containers:
   - name: nginx
     image: nginx:1.17-alpine
     
   - name: inspect
     image: alpine:3.9
     command: ["sleep","3600"]